### ISSUE TITLE
Testing and mocking guide?

### ISSUE THREAD

**Issue by avalanche-tm** [supabase-community/supabase-flutter#109]
Is there any guide on how to run code in tests or mock existing services? I tried to do something like this but I always get error 400. User does exist in database and running this same code in Flutter widget works perfectly.

```
 test('supabase test', () async {
    await Supabase.initialize(
      url: 'http://localhost:54321',
      anonKey: 'mykey',
      debug: true,
    );
    final res = await Supabase.instance.client.auth
        .signIn(email: 'user@example.com', password: 'test');
  });
```

**Comment by dshukertjr** [comment]
Hi @avalanche-tm,

We currently do not have a guide on running tests, but might be a good one for me to work on. I think it might make sense to create an easily mocking package for Supabase. 

In the mean while, the problem is that Flutter's test environment does not allow http request by default. There seems to be [a way of overriding this behavior](https://timm.preetz.name/articles/http-request-flutter-test).

**Comment by avalanche-tm** [comment]
> Hi @avalanche-tm,
> 
> We currently do not have a guide on running tests, but might be a good one for me to work on. I think it might make sense to create an easily mocking package for Supabase.
> 
> In the mean while, the problem is that Flutter's test environment does not allow http request by default. There seems to be [a way of overriding this behavior](https://timm.preetz.name/articles/http-request-flutter-test).

**Comment by avalanche-tm** [comment]
@dshukertjr Thank you very much for quick response and also for all the effort you've put into this project. It's great!

**Comment by NonymousMorlock** [comment]
> but might be a good one for me to work on

@dshukertjr  Did you happen to ?

**Comment by dshukertjr** [comment]
@NonymousMorlock 
No, haven't yet.

**Comment by NonymousMorlock** [comment]
@dshukertjr Alright Thanks

**Comment by msubodh** [comment]
Is there an ETA on this? Thanks
