### ISSUE TITLE
update to flutter 3 widget binding warnings

### ISSUE THREAD

**Issue by parkerhutchinson** [supabase-community/supabase-flutter#138]
current your package suffers from this issue in flutter. 

https://github.com/flutter/flutter/issues/103561#issuecomment-1126416045

**Comment by luilabdev** [comment]
Hey same warning here

Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null

src/supabase_auth_required_state.dart:43

Flutter 3.0.4
supabase_flutter: ^0.3.3

**Comment by oluwaseye** [comment]
Same here

**Comment by VittorioParagallo** [comment]
same here

**Comment by bdlukaa** [comment]
SupabaseAuthState was removed on the latest prereleases. Please upgrade your `supabase_flutter` to the latest prerelease

**Comment by dshukertjr** [comment]
Actually, there is still a warning, because we have [this](https://github.com/supabase-community/supabase-flutter/blob/main/lib/src/supabase_auth.dart#L124) code. 

## Anyone coming to this issue and leaving comments, please read this 👇
The message you are seeing is **just a waning**, and not an error. It is necessary to keep the `?` in there for backwards compatibility. You can read the official comment from the Flutter team [here](https://github.com/flutter/flutter/issues/103561#issuecomment-1126416045). 

If your app is not working, the cause is something else.
