### ISSUE TITLE
Insert no longer returning new record

### ISSUE THREAD

**Issue by JPM84** [supabase-community/supabase-flutter#164]
If I call `.insert` via the new **Supabase Flutter SDK 1.0 Developer Preview** the new record is no longer returned.
Instead I am receiving a `NULL` return. What am I missing?
By default, the new record was returned in previous supabase_flutter version.

**Comment by bdlukaa** [comment]
Can you post here a reproducible code? Are you using `ReturningOptions`?

**Comment by floodoo** [comment]
I have the same problem. The ```.insert``` function, doesn't have ```ReturningOptions``` and only returns ```NULL```. It also occurs when calling ```.upsert``` with ```FetchOptions(forceResponse: true)```

**Comment by JPM84** [comment]
Doing nothing special.
Just like in most examples `final response = await supabase.from('messages').insert({'message': 'foo'})`.

**Comment by dshukertjr** [comment]
@JPM84 @floodoo 
Sorry, there was a breaking change to the api there. `ReturningOptions` has been removed, and in order to retrieve the data after inserting, you now have to add a `select()` at the end of the query like this.

```dart
final data = await client.from('countries').insert({'name': 'France'}).select();
```

This makes it more intuitive for people getting started with Supabase, because most people do not expect to get any data in return when they are just inserting. Javascript SDK will undergo a similar breaking change as well pretty soon 😉

**Comment by Schnodderbalken** [comment]
@dshukertjr 
I would love this to be reflected in the API doc: https://supabase.com/docs/reference/dart/insert it's obsolete as it even recommends to use `execute()` which is deprecated.

**Comment by dshukertjr** [comment]
@Schnodderbalken 
Great point! Right now the library is in an intermediate state where the `1.0.0-dev.1`, but once it's released as a stable version, I will for sure update the  docs!

**Comment by JPM84** [comment]
Thanks for the quick explanation! Works as designed 👍.
An example project or documentation would help, especially when migrating from previous versions.
Anyhow just wanted to say the new implementation is really a great improvement!
