### ISSUE TITLE
Inability to use operators other than `eq` in the realtime filter within the `.from` argument

### ISSUE THREAD

**Issue by osaxma** [supabase-community/supabase-flutter#91]
When I use any operator other than `eq` in the `.from` argument, I get the following error:
  ```
  relation "<schema>.<table>:<column>=<operator>.<value>" does not exist`
  ```
For the following operators:  `neq`, `lt`, `lte`, `gt`, and  `gte`.

For  instance:
- This works:
  ```dart
  supabaseClient.from("messages:is_seen=eq.false") 
  ```

- This does not work:
  ```dart
  supabaseClient.from("messages:is_seen=neq.false") 
  ```
  It gives the following error:
   ```
   relation "public.messages:is_seen=neq.false" does not exist
   ```

**Versions**
- supabase: ^0.2.13
- flutter: 2.8.1

**Comment by VittorioParagallo** [comment]
Couples of weeks ago i filed this: [More filters on Realtime query #180](https://github.com/supabase-community/supabase-flutter/issues/180)
I checked with an hack if it possible to have more and different filters. It turned out that it is possible to get the query results filtered but the server will fire events filtered only on the first eq. So i propose to use it anyway and meanwhile it is implemented server side we can discard not filtered events. But the developer said that they prefer to be consistent with the server api, which makes sense. 
But i'ld really like to push this

**Comment by dshukertjr** [comment]
Closing this for now as we have to wait for the realtime server to introduce additional filter compatibility.

**Comment by dshukertjr** [comment]
Okay, turns out that realtime team is done implementing additional filters on the backend. Will reopen this and we will start implementing these filters.
https://github.com/supabase/realtime/issues/222#issuecomment-1258445881
